# Generated by Django 4.2.30 on 2026-06-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='reference',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
